package es.uca.iw.views;

import es.uca.iw.MainLayout;
import es.uca.iw.domain.Cliente;
import es.uca.iw.domain.User;
import es.uca.iw.security.AuthenticatedUser;
import es.uca.iw.services.ClienteService;
import es.uca.iw.services.PdfService;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.Optional;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.HasValue;
import com.vaadin.flow.component.HasValue.ValueChangeListener;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Hr;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.menubar.MenuBar;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.server.StreamResource;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import jakarta.annotation.security.PermitAll;
import jakarta.annotation.security.RolesAllowed;

@PageTitle("Mi Zona")
@Route(value = "mi-zona", layout = MainLayout.class)
@RolesAllowed("CLIENTE")
@Uses(Icon.class)
public class UserMiZonaView extends Composite<VerticalLayout> {

    private AuthenticatedUser authenticatedUser;
    private ClienteService clienteService;
    private Button ContactaButton = new Button("Contacta con nosotros");

    public UserMiZonaView(AuthenticatedUser authenticatedUser, ClienteService clienteService) {
        this.authenticatedUser = authenticatedUser;
        this.clienteService = clienteService;
        H2 txtServiciosOfertados = new H2();
        HorizontalLayout layoutRow = new HorizontalLayout();
        VerticalLayout layoutColumn2 = new VerticalLayout();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        HorizontalLayout layoutRow5 = new HorizontalLayout();
        HorizontalLayout layoutRow6 = new HorizontalLayout();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        HorizontalLayout layoutRow7 = new HorizontalLayout();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        HorizontalLayout layoutRow8 = new HorizontalLayout();
        HorizontalLayout layoutRow9 = new HorizontalLayout();
        HorizontalLayout layoutRow10 = new HorizontalLayout();
        HorizontalLayout layoutRow11 = new HorizontalLayout();
        VerticalLayout layoutColumn5 = new VerticalLayout();
        HorizontalLayout layoutRow12 = new HorizontalLayout();
        HorizontalLayout layoutRow13 = new HorizontalLayout();
        HorizontalLayout layoutRow14 = new HorizontalLayout();
        HorizontalLayout layoutRow15 = new HorizontalLayout();
        VerticalLayout layoutColumn6 = new VerticalLayout();
        HorizontalLayout layoutRow16 = new HorizontalLayout();
        HorizontalLayout layoutRow17 = new HorizontalLayout();
        HorizontalLayout layoutRow18 = new HorizontalLayout();
        HorizontalLayout layoutRow19 = new HorizontalLayout();
        HorizontalLayout layoutRow20 = new HorizontalLayout();
        Button buttonPrimary = new Button();
        Hr hr = new Hr();
        H2 h25 = new H2();
        Hr hr2 = new Hr();
        H2 h26 = new H2();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        txtServiciosOfertados.setText("Servicios ofertados");
        txtServiciosOfertados.setWidth("max-content");
        layoutRow.setWidthFull();
        getContent().setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.setHeight("min-content");
        layoutColumn2.setHeightFull();
        layoutRow.setFlexGrow(1.0, layoutColumn2);
        layoutColumn2.setWidth("100%");
        layoutColumn2.setHeight("100%");
        layoutColumn2.setJustifyContentMode(JustifyContentMode.START);
        layoutColumn2.setAlignItems(Alignment.START);
        layoutRow2.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.getStyle().set("flex-grow", "1");
        layoutRow3.setHeightFull();
        layoutRow2.setFlexGrow(1.0, layoutRow3);
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.setWidth("100%");
        layoutRow3.getStyle().set("flex-grow", "1");
        layoutRow3.setAlignItems(Alignment.CENTER);
        layoutRow3.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow4.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow4);
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.setWidth("100%");
        layoutRow4.getStyle().set("flex-grow", "1");
        layoutRow4.setAlignItems(Alignment.CENTER);
        layoutRow4.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow5.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow5);
        layoutRow5.addClassName(Gap.MEDIUM);
        layoutRow5.setWidth("100%");
        layoutRow5.getStyle().set("flex-grow", "1");
        layoutRow5.setAlignItems(Alignment.CENTER);
        layoutRow5.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow6.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow6);
        layoutRow6.addClassName(Gap.MEDIUM);
        layoutRow6.setWidth("100%");
        layoutRow6.getStyle().set("flex-grow", "1");
        layoutRow6.setAlignItems(Alignment.CENTER);
        layoutRow6.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn3.setHeightFull();
        layoutRow.setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.setWidth("100%");
        layoutColumn3.setHeight("100%");
        layoutColumn3.setJustifyContentMode(JustifyContentMode.START);
        layoutColumn3.setAlignItems(Alignment.START);
        layoutRow7.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow7);
        layoutRow7.addClassName(Gap.MEDIUM);
        layoutRow7.setWidth("100%");
        layoutRow7.getStyle().set("flex-grow", "1");
        layoutColumn4.setHeightFull();
        layoutRow7.setFlexGrow(1.0, layoutColumn4);
        layoutColumn4.setWidth("100%");
        layoutColumn4.getStyle().set("flex-grow", "1");
        layoutRow8.setWidthFull();
        layoutColumn4.setFlexGrow(1.0, layoutRow8);
        layoutRow8.addClassName(Gap.MEDIUM);
        layoutRow8.setWidth("100%");
        layoutRow8.getStyle().set("flex-grow", "1");
        layoutRow8.setAlignItems(Alignment.CENTER);
        layoutRow8.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow9.setWidthFull();
        layoutColumn4.setFlexGrow(1.0, layoutRow9);
        layoutRow9.addClassName(Gap.MEDIUM);
        layoutRow9.setWidth("100%");
        layoutRow9.getStyle().set("flex-grow", "1");
        layoutRow9.setAlignItems(Alignment.CENTER);
        layoutRow9.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow10.setWidthFull();
        layoutColumn4.setFlexGrow(1.0, layoutRow10);
        layoutRow10.addClassName(Gap.MEDIUM);
        layoutRow10.setWidth("100%");
        layoutRow10.getStyle().set("flex-grow", "1");
        layoutRow10.setAlignItems(Alignment.CENTER);
        layoutRow10.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow11.setWidthFull();
        layoutColumn4.setFlexGrow(1.0, layoutRow11);
        layoutRow11.addClassName(Gap.MEDIUM);
        layoutRow11.setWidth("100%");
        layoutRow11.getStyle().set("flex-grow", "1");
        layoutRow11.setAlignItems(Alignment.CENTER);
        layoutRow11.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn5.setHeightFull();
        layoutRow7.setFlexGrow(1.0, layoutColumn5);
        layoutColumn5.setWidth("100%");
        layoutColumn5.getStyle().set("flex-grow", "1");
        layoutRow12.setWidthFull();
        layoutColumn5.setFlexGrow(1.0, layoutRow12);
        layoutRow12.addClassName(Gap.MEDIUM);
        layoutRow12.setWidth("100%");
        layoutRow12.getStyle().set("flex-grow", "1");
        layoutRow12.setAlignItems(Alignment.CENTER);
        layoutRow12.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow13.setWidthFull();
        layoutColumn5.setFlexGrow(1.0, layoutRow13);
        layoutRow13.addClassName(Gap.MEDIUM);
        layoutRow13.setWidth("100%");
        layoutRow13.getStyle().set("flex-grow", "1");
        layoutRow13.setAlignItems(Alignment.CENTER);
        layoutRow13.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow14.setWidthFull();
        layoutColumn5.setFlexGrow(1.0, layoutRow14);
        layoutRow14.addClassName(Gap.MEDIUM);
        layoutRow14.setWidth("100%");
        layoutRow14.getStyle().set("flex-grow", "1");
        layoutRow14.setAlignItems(Alignment.CENTER);
        layoutRow14.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow15.setWidthFull();
        layoutColumn5.setFlexGrow(1.0, layoutRow15);
        layoutRow15.addClassName(Gap.MEDIUM);
        layoutRow15.setWidth("100%");
        layoutRow15.getStyle().set("flex-grow", "1");
        layoutRow15.setAlignItems(Alignment.CENTER);
        layoutRow15.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn6.setHeightFull();
        layoutRow.setFlexGrow(1.0, layoutColumn6);
        layoutColumn6.setWidth("100%");
        layoutColumn6.setHeight("100%");
        layoutColumn6.setJustifyContentMode(JustifyContentMode.START);
        layoutColumn6.setAlignItems(Alignment.START);
        layoutRow16.setWidthFull();
        layoutColumn6.setFlexGrow(1.0, layoutRow16);
        layoutRow16.addClassName(Gap.MEDIUM);
        layoutRow16.setWidth("100%");
        layoutRow16.getStyle().set("flex-grow", "1");
        layoutRow17.setHeightFull();
        layoutRow16.setFlexGrow(1.0, layoutRow17);
        layoutRow17.addClassName(Gap.MEDIUM);
        layoutRow17.setWidth("100%");
        layoutRow17.getStyle().set("flex-grow", "1");
        layoutRow17.setAlignItems(Alignment.CENTER);
        layoutRow17.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow18.setWidthFull();
        layoutColumn6.setFlexGrow(1.0, layoutRow18);
        layoutRow18.addClassName(Gap.MEDIUM);
        layoutRow18.setWidth("100%");
        layoutRow18.getStyle().set("flex-grow", "1");
        layoutRow18.setAlignItems(Alignment.CENTER);
        layoutRow18.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow19.setWidthFull();
        layoutColumn6.setFlexGrow(1.0, layoutRow19);
        layoutRow19.addClassName(Gap.MEDIUM);
        layoutRow19.setWidth("100%");
        layoutRow19.getStyle().set("flex-grow", "1");
        layoutRow19.setAlignItems(Alignment.CENTER);
        layoutRow19.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow20.setWidthFull();
        layoutColumn6.setFlexGrow(1.0, layoutRow20);
        layoutRow20.addClassName(Gap.MEDIUM);
        layoutRow20.setWidth("100%");
        layoutRow20.getStyle().set("flex-grow", "1");
        layoutRow20.setAlignItems(Alignment.CENTER);
        layoutRow20.setJustifyContentMode(JustifyContentMode.CENTER);
        getContent().setAlignSelf(FlexComponent.Alignment.CENTER, ContactaButton);
        buttonPrimary.setText("Actualizar contrato");
        buttonPrimary.setEnabled(false); // Deshabilitar el botón al principio
        buttonPrimary.getStyle().set("background-color", "grey"); // Cambiar el color a gris
        getContent().setAlignSelf(FlexComponent.Alignment.CENTER, buttonPrimary);
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonPrimary.addClickListener(event -> {
            Notification.show("Su contrato se ha actualizado");
        });
        h25.setText("Consumo de datos 5G");
        h25.setWidth("max-content");
        h26.setText("Desglose de llamadas");
        h26.setWidth("max-content");

        getContent().add(txtServiciosOfertados);
        getContent().add(layoutRow);
        layoutRow.add(layoutColumn2);
        layoutColumn2.add(layoutRow2);
        layoutRow2.add(layoutRow3);
        layoutColumn2.add(layoutRow4);
        layoutColumn2.add(layoutRow5);
        layoutColumn2.add(layoutRow6);
        layoutRow.add(layoutColumn3);
        layoutColumn3.add(layoutRow7);
        layoutRow7.add(layoutColumn4);
        layoutColumn4.add(layoutRow8);
        layoutColumn4.add(layoutRow9);
        layoutColumn4.add(layoutRow10);
        layoutColumn4.add(layoutRow11);
        layoutRow7.add(layoutColumn5);
        layoutColumn5.add(layoutRow12);
        layoutColumn5.add(layoutRow13);
        layoutColumn5.add(layoutRow14);
        layoutColumn5.add(layoutRow15);
        layoutRow.add(layoutColumn6);
        layoutColumn6.add(layoutRow16);
        layoutRow16.add(layoutRow17);
        layoutColumn6.add(layoutRow18);
        layoutColumn6.add(layoutRow19);
        layoutColumn6.add(layoutRow20);
        getContent().add(ContactaButton);
        getContent().add(buttonPrimary);

        Optional<User> maybeUser = this.authenticatedUser.get();
        if (maybeUser.isPresent()) {
            User user = maybeUser.get();
            Cliente cliente = clienteService.loadClienteById(user.getId());
            StreamResource pdfResource = PdfService.generarFactura(cliente);
            com.vaadin.flow.component.html.Anchor downloadLink = new com.vaadin.flow.component.html.Anchor(pdfResource, "Generar Factura");
            downloadLink.setTarget("_blank");
            getContent().setAlignSelf(FlexComponent.Alignment.CENTER, downloadLink);
            getContent().add(downloadLink);
        }

        getContent().add(hr);
        getContent().add(h25);
        getContent().add(hr2);
        getContent().add(h26);

        ContactaButton.addClickListener(event -> {
            UI.getCurrent().navigate("/consultas");
        });
       
    }
}