name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code, setup Maven, cache dependencies and more...
        uses: s4u/setup-maven-action@v1.10.0
        with:
          java-distribution: 'temurin'
          java-version: '17'

      - name: Get Artifact version from pom.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion

      - name: Build with Maven and analyze with Sonar Cloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean -Dmaven.test.skip=true -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=Paco-PE_iw2023-2024-UFJMOVIL -Dsonar.organization=paco-pe
      - name: Build and Deploy to GitHub Packages
        run: mvn deploy -Dmaven.test.skip=true -U -B -Pproduction
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Rename jar file
        run: mv target/*.jar target/ujfmovil.jar

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: UFJMOVIL   # Configurar nombre de la app
          environment_name: UFJMOVIL-prod  # Configurar nombre del entorno
          region: us-east-1 # Configurar región
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          version_label: ${{ steps.getVersion.outputs.version }}
          version_description: ${{github.SHA}}
          deployment_package: target/ujfmovil.jar
          use_existing_version_if_available: true

